#pragma once
#include "Object.h"
#include "CollisionQueryParams.h"
#include "Math/Rotator.h"
#include "Math/Color.h"

namespace EDrawDebugTrace { enum Type { None, ForOneFrame, ForDuration, Persistent }; }

class ENGINE_API UKismetSystemLibrary
{
public:
    static void FlushPersistentDebugLines(const UObject* _WorldContextObject);
    static bool LineTraceSingle(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool LineTraceMulti(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool LineTraceSingleForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool LineTraceMultiForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool LineTraceSingleByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool LineTraceMultiByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceSingle(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceMulti(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceSingleForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceMultiForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceSingleByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxTraceMultiByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, const FVector _HalfSize, const FRotator _Orientation, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceSingle(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceMulti(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceSingleForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceMultiForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceSingleByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool SphereTraceMultiByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceSingle(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceMulti(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, ETraceTypeQuery _TraceChannel, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceSingleForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceMultiForObjects(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, const std::vector<EObjectTypeQuery>& _ObjectTypes, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceSingleByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, FHitResult& _OutHit, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool CapsuleTraceMultiByProfile(const UObject* _WorldContextObject, const FVector _Start, const FVector _End, float _Radius, float _HalfHeight, FName _ProfileName, bool _bTraceComplex, const std::vector<AActor*>& _ActorsToIgnore, EDrawDebugTrace::Type _DrawDebugType, std::vector<FHitResult>& _OutHits, bool _bIgnoreSelf, FLinearColor _TraceColor = FLinearColor::Red, FLinearColor _TraceHitColor = FLinearColor::Green, float _DrawTime = 5.0f);
    static bool BoxOverlapActors(const UObject* _WorldContextObject, const FVector _Pos, FVector _BoxExtent, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<AActor*>& _OutActors);
    static bool BoxOverlapComponents(const UObject* _WorldContextObject, const FVector _Pos, FVector _BoxExtent, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<UPrimitiveComponent*>& _OutComponents);
    static bool SphereOverlapActors(const UObject* _WorldContextObject, const FVector _Pos, float _Radius, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<AActor*>& _OutActors);
    static bool SphereOverlapComponents(const UObject* _WorldContextObject, const FVector _Pos, float _Radius, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<UPrimitiveComponent*>& _OutComponents);
    static bool CapsuleOverlapActors(const UObject* _WorldContextObject, const FVector _Pos, float _Radius, float _HalfHeight, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<AActor*>& _OutActors);
    static bool CapsuleOverlapComponents(const UObject* _WorldContextObject, const FVector _Pos, float _Radius, float _HalfHeight, const std::vector<EObjectTypeQuery>& _ObjectTypes, UClass* _ClassFilter, const std::vector<AActor*>& _ActorsToIgnore, std::vector<UPrimitiveComponent*>& _OutComponents);
};
